services:

  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
    env_file:
      - env/rabbitmq_server.env

  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    hostname: influxdb
    ports:
      - 8086:8086
    env_file:
      - env/influxdb_server.env
  
  simulator_mock:
    image: "chronis10/teaching-sensors:${ARCH:-amd64}"
    container_name: simulator_mock
    depends_on: 
      - rabbitmq
    restart: on-failure
    environment:
      - SERVICE_TYPE=file.csv_feed.CSVFeed
      - SERVICE_NAME=simulator_mock
      - FILE_PATH=raw_data/s4181xsport.csv
      - TRANSMIT_RATE=0.1
      - OUTPUT_TOPIC=sensor.simulator.value
    env_file:
      - env/rabbitmq_client.env
    volumes:
      - $PWD/dataset/s4181xsport.csv:/app/raw_data/s4181xsport.csv
 
  rl_predictor:
    image: "chronis10/teaching-ai-toolkit:${ARCH:-amd64}"
    container_name: rl_predictor
    depends_on: 
      - rabbitmq
    restart: on-failure
    environment:
      - SERVICE_TYPE=modules.rl_graz_module.RLModule
      - SERVICE_NAME=rl_graz_module
      - TOPICS=sensor.simulator.value
      - MODEL_PATH=/app/storage/s4181_model.h5
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
    env_file:
      - env/rabbitmq_client.env
    volumes:
      - $PWD/model/s4181_model.h5:/app/storage/s4181_model.h5
      - $PWD/custom_modules/rl_graz_module.py:/app/modules/rl_graz_module.py
    
  
  influxdb_logger:
    image: "chronis10/teaching-data:${ARCH:-amd64}"
    container_name: influxdb_logger
    depends_on:
      - rabbitmq
      - influxdb
    restart: on-failure
    environment:
      - SERVICE_TYPE=influxdb.client.InfluxDBClientHandler
      - SERVICE_NAME=influxdb_logger
      - TOPICS=*.*.value
    env_file:
      - env/rabbitmq_client.env
      - env/influxdb_client.env